### ISSUE TITLE
Plugin doesnt' working with 2.6 release

### ISSUE THREAD

**Issue by ronlinet** [CakeDC/tags#98] opened 2015-01-30 09:11 UTC
After extracting the plugin in to app/Plugin/Tags, I am stuck with database installation. 
The “cake schema create --plugin Tags” throws bunch of errors and tables are not installed. 
Is this plugin supposed to work with 2.6 release?

**Comment by dithmarschen77** [comment] 2015-02-07 19:21
You can get the create table statements from the config/schema.php

DROP TABLE IF EXISTS `tagged`;

CREATE TABLE `tagged` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `foreign_key` varchar(36) NOT NULL,
  `tag_id` varchar(36) NOT NULL,
  `model` varchar(255) NOT NULL,
  `language` varchar(6) DEFAULT NULL,
  `times_tagged` int(11) NOT NULL DEFAULT '1',
  `created` datetime DEFAULT NULL,
  `modified` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UNIQUE_TAGGING` (`model`,`foreign_key`,`tag_id`,`language`),
  KEY `INDEX_TAGGED` (`model`),
  KEY `INDEX_LANGUAGE` (`language`)
);

DROP TABLE IF EXISTS `tags`;

CREATE TABLE `tags` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `identifier` varchar(30) DEFAULT NULL,
  `name` varchar(30) NOT NULL,
  `keyname` varchar(30) NOT NULL,
  `created` datetime DEFAULT NULL,
  `modified` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UNIQUE_TAG` (`identifier`,`keyname`)
);

**Comment by antoniovassell** [comment] 2015-05-29 09:10
Hey @ronlinet, whenever stating an issue, can you state exactly what the issue is? What does "bunch of errors" mean? Issues like this you should paste the errors at all times.

**Comment by steinkel** [comment] 2015-10-22 15:01
Closing this issue, please let us know if any other issue detected. Thank you.

**Closed by steinkel** 2015-10-22 15:01 UTC
