### ISSUE TITLE
The Tag Cloud Helper Database Error: Unknown column 'Tag.weight' in 'field list' (cakePHP 2.5)

### ISSUE THREAD

**Issue by maniekx1984** [CakeDC/tags#121] opened 2017-05-29 19:05 UTC
Hi, after adding Tag Cloud like here https://github.com/CakeDC/tags/blob/master/Docs/Documentation/The-Tag-Cloud-Helper.md there is an Error:
Database Error
Error: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Tag.weight' in 'field list'

**Comment by rogerpro** [comment] 2017-12-04 19:40
Hi, I did a test to check if the issue is still happening. Everything was as expected.

I set an app with an articles table, then installed tags plugin, tagged, and included a tag cloud in articles/index. Tags appear with no errors.

I used latest version of the framework: CakePHP 2.10.5

You can try it from my repo: just clone, set a DB & run migrations from https://github.com/rogerpro/test-cake2-tags

Can you confirm if you are still having issues? Thanks.

**Comment by maniekx1984** [comment] 2017-12-04 22:04
Hi,

I’ve found that in tags/Config/Schema/schema.php ‘tags’ table is without ‘weight’ column (which can be found in ‘Migration’). I’ve needed to create MySQL table manually and I’ve checked schema.php file as a guide.

After updating MySQL with ‘weight’ column it works fine.

Thanks
Kuba

**Comment by rogerpro** [comment] 2017-12-05 12:26
@maniekx1984 notice that actually `weight ` column is not present after running all migrations https://github.com/CakeDC/tags/blob/develop/Config/Migration/003_occurrence_fields_for_tags.php#L47 -- field is dropped on 3rd migration.

We'll release soon. Then, please recheck with latest Tags plugin & latest CakePHP 2.10.5 and report any error with its trace.

**Comment by andrej-griniuk** [comment] 2017-12-08 11:15
The fix was merged to develop branch. Release comes out soon.

**Closed as completed by andrej-griniuk** 2017-12-08 11:15 UTC
